"""
QueryMind - File Generator Service
Provides format conversion and export utilities:
- Conversation -> Markdown, JSON, PDF
- Knowledge Items -> CSV, JSON, Markdown
- Cross-Document Analysis -> Markdown, PDF, JSON
- In-memory ZIP packaging for bulk downloads and exports
"""

import io
import csv
import json
import zipfile
from datetime import datetime, timezone
from typing import List, Tuple, Dict, Any, Union, Optional

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    HRFlowable,
    KeepTogether,
    Table,
    TableStyle,
)


class FileGenerator:
    """Utility class for generating files and archives across various formats."""

    @staticmethod
    def conversation_to_markdown(
        conversation_title: str,
        conversation_id: str,
        created_at: datetime,
        messages: List[Any],
        include_citations: bool = True,
    ) -> str:
        """Converts conversation and its messages into clean GitHub-flavored markdown."""
        date_str = created_at.strftime("%Y-%m-%d %H:%M:%S UTC") if created_at else "Unknown"
        lines = [
            f"# {conversation_title or 'Conversation Export'}",
            "",
            f"- **Session ID:** `{conversation_id}`",
            f"- **Exported At:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"- **Created At:** {date_str}",
            "",
            "---",
            "",
        ]

        for idx, msg in enumerate(messages, 1):
            role = getattr(msg, "role", "user")
            content = getattr(msg, "content", "")
            citations = getattr(msg, "citations", None)
            timestamp = getattr(msg, "created_at", None)
            time_tag = f" ({timestamp.strftime('%H:%M:%S')})" if timestamp else ""

            role_heading = "### 👤 User" if role.lower() == "user" else "### 🤖 QueryMind Assistant"
            lines.append(f"{role_heading}{time_tag}\n")
            lines.append(f"{content}\n")

            if include_citations and citations and isinstance(citations, list) and len(citations) > 0:
                lines.append("> **Sources & Citations:**")
                for c in citations:
                    if isinstance(c, dict):
                        doc_title = c.get("document_title") or c.get("title") or c.get("source") or "Document"
                        snippet = c.get("text") or c.get("content") or c.get("snippet") or ""
                        page = c.get("page")
                        page_info = f" (Page {page})" if page else ""
                        if snippet:
                            lines.append(f"> - **{doc_title}{page_info}:** {snippet[:180]}...")
                        else:
                            lines.append(f"> - **{doc_title}{page_info}**")
                lines.append("")

            lines.append("---\n")

        lines.append("\n*Generated by QueryMind Autonomous Knowledge Workspace.*")
        return "\n".join(lines)

    @staticmethod
    def conversation_to_json(
        conversation_title: str,
        conversation_id: str,
        space_id: str,
        created_at: datetime,
        messages: List[Any],
        include_citations: bool = True,
    ) -> str:
        """Converts conversation into structured JSON."""
        payload = {
            "conversation_id": str(conversation_id),
            "space_id": str(space_id),
            "title": conversation_title,
            "created_at": created_at.isoformat() if created_at else None,
            "exported_at": datetime.now(timezone.utc).isoformat(),
            "messages": [
                {
                    "id": str(getattr(m, "id", "")),
                    "role": getattr(m, "role", "user"),
                    "content": getattr(m, "content", ""),
                    "citations": getattr(m, "citations", None) if include_citations else None,
                    "metadata": getattr(m, "metadata_json", None),
                    "created_at": getattr(m, "created_at", datetime.now(timezone.utc)).isoformat()
                    if getattr(m, "created_at", None)
                    else None,
                }
                for m in messages
            ],
        }
        return json.dumps(payload, indent=2, ensure_ascii=False)

    @staticmethod
    def conversation_to_pdf(
        conversation_title: str,
        conversation_id: str,
        created_at: datetime,
        messages: List[Any],
        include_citations: bool = True,
    ) -> bytes:
        """Renders conversation to styled PDF bytes using ReportLab."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#111827"),
            spaceAfter=6,
        )

        meta_style = ParagraphStyle(
            "DocMeta",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#6B7280"),
            spaceAfter=14,
        )

        user_role_style = ParagraphStyle(
            "UserRole",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#2563EB"),
            spaceBefore=10,
            spaceAfter=4,
        )

        assistant_role_style = ParagraphStyle(
            "AssistantRole",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#10B981"),
            spaceBefore=10,
            spaceAfter=4,
        )

        body_style = ParagraphStyle(
            "MsgBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#1F2937"),
            spaceAfter=8,
        )

        citation_style = ParagraphStyle(
            "CitationStyle",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#4B5563"),
            leftIndent=12,
            spaceAfter=4,
        )

        story = []

        # Document Header
        story.append(Paragraph(conversation_title or "Conversation Session", title_style))
        created_str = created_at.strftime("%Y-%m-%d %H:%M:%S UTC") if created_at else "N/A"
        story.append(
            Paragraph(
                f"ID: {conversation_id} &bull; Created: {created_str} &bull; Exported: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
                meta_style,
            )
        )
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB"), spaceAfter=12))

        # Messages Flow
        for msg in messages:
            role = getattr(msg, "role", "user")
            content = getattr(msg, "content", "")
            citations = getattr(msg, "citations", None)

            is_user = role.lower() == "user"
            role_label = "User" if is_user else "QueryMind Assistant"
            story.append(Paragraph(role_label, user_role_style if is_user else assistant_role_style))

            # Escape HTML characters in message body for ReportLab Paragraph
            safe_content = (
                content.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\n", "<br/>")
            )
            story.append(Paragraph(safe_content, body_style))

            if include_citations and citations and isinstance(citations, list) and len(citations) > 0:
                story.append(Paragraph("<b>Sources &amp; Citations:</b>", citation_style))
                for c in citations:
                    if isinstance(c, dict):
                        doc_name = (
                            c.get("document_title") or c.get("title") or c.get("source") or "Document"
                        )
                        safe_doc = doc_name.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                        text_snip = (c.get("text") or c.get("content") or "")[:120].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                        story.append(
                            Paragraph(f"&bull; <i>{safe_doc}:</i> {text_snip}", citation_style)
                        )

            story.append(Spacer(1, 8))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#F3F4F6"), spaceAfter=8))

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    @staticmethod
    def knowledge_to_csv(knowledge_items: List[Dict[str, Any]]) -> str:
        """Converts knowledge items into CSV table."""
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["id", "entity_or_concept", "knowledge_type", "content", "confidence", "created_at"])

        for k in knowledge_items:
            writer.writerow([
                k.get("id", ""),
                k.get("concept", k.get("title", "")),
                k.get("type", "fact"),
                k.get("content", k.get("description", "")),
                k.get("confidence", 1.0),
                k.get("created_at", ""),
            ])

        return output.getvalue()

    @staticmethod
    def knowledge_to_json(knowledge_items: List[Dict[str, Any]]) -> str:
        """Converts knowledge items into formatted JSON."""
        return json.dumps(knowledge_items, indent=2, ensure_ascii=False)

    @staticmethod
    def knowledge_to_markdown(knowledge_items: List[Dict[str, Any]]) -> str:
        """Converts knowledge items into structured Markdown."""
        lines = [
            "# QueryMind Knowledge Vault Export",
            f"Exported: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"Total Items: {len(knowledge_items)}",
            "",
            "---",
            "",
        ]

        for k in knowledge_items:
            title = k.get("concept") or k.get("title") or "Knowledge Item"
            k_type = k.get("type", "fact")
            content = k.get("content") or k.get("description") or ""
            confidence = k.get("confidence", 1.0)
            date_val = k.get("created_at", "")

            lines.append(f"### {title} `[{k_type.upper()}]`")
            if date_val:
                lines.append(f"- **Recorded:** {date_val}")
            lines.append(f"- **Confidence:** {confidence}")
            lines.append(f"\n{content}\n")
            lines.append("---")
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def analysis_to_markdown(analysis_data: Dict[str, Any], title: str = "Cross-Document Analysis Report") -> str:
        """Formats cross-document analysis payload into executive markdown report."""
        lines = [
            f"# {title}",
            "",
            f"- **Generated At:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"- **Target Documents:** {analysis_data.get('documents_analyzed_count', 'N/A')}",
            "",
            "## Executive Summary",
            "",
            analysis_data.get("executive_summary", "No summary provided."),
            "",
            "---",
            "",
        ]

        # Key Patterns Across Documents
        patterns = analysis_data.get("patterns", [])
        if patterns:
            lines.append("## 🔍 Shared Patterns & Common Themes")
            lines.append("")
            for p in patterns:
                p_title = p.get("title") or "Pattern"
                desc = p.get("description") or ""
                sources = p.get("source_documents", [])
                source_str = f" *(Sources: {', '.join(sources)})*" if sources else ""
                lines.append(f"### • {p_title}{source_str}")
                lines.append(f"{desc}\n")
            lines.append("---")
            lines.append("")

        # Temporal Trends & Evolution
        trends = analysis_data.get("trends", [])
        if trends:
            lines.append("## 📈 Temporal Trends & Evolutions")
            lines.append("")
            for t in trends:
                metric = t.get("metric") or t.get("topic") or "Trend"
                direction = t.get("direction", "neutral")
                desc = t.get("description") or ""
                emoji = "↗️" if direction == "up" else "↘️" if direction == "down" else "➡️"
                lines.append(f"### {emoji} {metric} ({direction.upper()})")
                lines.append(f"{desc}\n")
            lines.append("---")
            lines.append("")

        # Contradictions & Divergences
        contradictions = analysis_data.get("contradictions", [])
        if contradictions:
            lines.append("## ⚠️ Divergences & Contradictions")
            lines.append("")
            for c in contradictions:
                issue = c.get("issue") or "Divergence"
                details = c.get("description") or ""
                resolution = c.get("suggested_resolution") or ""
                lines.append(f"### ⚡ {issue}")
                lines.append(f"{details}")
                if resolution:
                    lines.append(f"\n> **Suggested Resolution:** {resolution}\n")
            lines.append("---")
            lines.append("")

        # Strategic Recommendations
        recommendations = analysis_data.get("recommendations", [])
        if recommendations:
            lines.append("## 💡 Strategic Recommendations")
            lines.append("")
            for idx, r in enumerate(recommendations, 1):
                lines.append(f"{idx}. {r}")
            lines.append("")

        lines.append("\n*Generated by QueryMind Multi-Agent Analysis Engine.*")
        return "\n".join(lines)

    @staticmethod
    def analysis_to_pdf(analysis_data: Dict[str, Any], title: str = "Cross-Document Analysis Report") -> bytes:
        """Renders cross-document analysis into professional PDF bytes."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#111827"),
            spaceAfter=6,
        )

        h2_style = ParagraphStyle(
            "H2",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#1E3A8A"),
            spaceBefore=12,
            spaceAfter=6,
        )

        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#1F2937"),
            spaceAfter=8,
        )

        story = []
        story.append(Paragraph(title, title_style))
        story.append(
            Paragraph(
                f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} &bull; QueryMind Intelligence",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 10))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=12))

        # Executive Summary
        story.append(Paragraph("Executive Summary", h2_style))
        summary_text = (
            analysis_data.get("executive_summary", "No summary.")
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\n", "<br/>")
        )
        story.append(Paragraph(summary_text, body_style))

        # Patterns
        patterns = analysis_data.get("patterns", [])
        if patterns:
            story.append(Paragraph("Cross-Document Patterns", h2_style))
            for p in patterns:
                p_title = p.get("title", "Pattern").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                desc = p.get("description", "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(f"<b>&bull; {p_title}:</b> {desc}", body_style))

        # Trends
        trends = analysis_data.get("trends", [])
        if trends:
            story.append(Paragraph("Identified Trends", h2_style))
            for t in trends:
                topic = (t.get("topic") or t.get("metric", "Trend")).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                desc = t.get("description", "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(f"<b>&bull; {topic}:</b> {desc}", body_style))

        # Contradictions
        contradictions = analysis_data.get("contradictions", [])
        if contradictions:
            story.append(Paragraph("Divergences &amp; Contradictions", h2_style))
            for c in contradictions:
                issue = c.get("issue", "Divergence").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                desc = c.get("description", "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(f"<b>&bull; {issue}:</b> {desc}", body_style))

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    @staticmethod
    def create_zip_archive(files: List[Tuple[str, Union[bytes, str]]]) -> bytes:
        """
        Creates an in-memory ZIP archive from a list of (filename, content_bytes_or_str).
        """
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
            for filename, content in files:
                if isinstance(content, str):
                    data = content.encode("utf-8")
                else:
                    data = content
                zf.writestr(filename, data)

        zip_buffer.seek(0)
        return zip_buffer.getvalue()

    @staticmethod
    def custom_document_to_pdf(
        title: str,
        content: str,
        author: Optional[str] = None,
    ) -> bytes:
        """
        Generates a standalone, beautifully styled PDF document from custom text/markdown.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=48,
            leftMargin=48,
            topMargin=48,
            bottomMargin=48,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#111827"),
            spaceAfter=6,
        )

        meta_style = ParagraphStyle(
            "DocMeta",
            parent=styles["Normal"],
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#6B7280"),
            spaceAfter=12,
        )

        body_style = ParagraphStyle(
            "DocBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=14.5,
            textColor=colors.HexColor("#1F2937"),
            spaceAfter=10,
        )

        story = []

        safe_title = (title or "Document").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        story.append(Paragraph(safe_title, title_style))

        meta_parts = [f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"]
        if author:
            safe_author = author.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            meta_parts.append(f"Author / Recipient: {safe_author}")
        meta_parts.append("QueryMind Knowledge Workspace")

        story.append(Paragraph(" &bull; ".join(meta_parts), meta_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB"), spaceAfter=14))

        # Split content into paragraphs
        paragraphs = content.split("\n\n")
        for p in paragraphs:
            p_clean = p.strip()
            if not p_clean:
                continue
            safe_p = (
                p_clean.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\n", "<br/>")
            )
            story.append(Paragraph(safe_p, body_style))

        story.append(Spacer(1, 16))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB"), spaceAfter=8))
        story.append(
            Paragraph(
                "<i>Document produced programmatically by QueryMind Knowledge Operating System.</i>",
                meta_style,
            )
        )

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

