"""step5_schema

Revision ID: df80c4d21d48
Revises: 9f9c7300c1df
Create Date: 2026-08-23 17:38:30.748735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df80c4d21d48'
down_revision: Union[str, None] = '9f9c7300c1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('task_id', sa.String(length=100), nullable=True))
    op.alter_column('agent_runs', 'output_summary',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='to_jsonb(output_summary)')
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('idx_knowledge_document_id', table_name='knowledge', if_exists=True)
    op.drop_index('idx_knowledge_source_chunk_id', table_name='knowledge', if_exists=True)
    op.drop_index('idx_knowledge_space_id', table_name='knowledge', if_exists=True)
    op.drop_index('idx_knowledge_user_id', table_name='knowledge', if_exists=True)
    op.drop_index('idx_spaces_user_one_default', table_name='spaces', postgresql_where='(is_default = true)', if_exists=True)
    op.drop_index('idx_spaces_user_slug', table_name='spaces', postgresql_where='(slug IS NOT NULL)', if_exists=True)
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_auth_users")
    op.add_column('workflow_steps', sa.Column('iteration', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'iteration')
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    spaces_cols = {c["name"] for c in inspector.get_columns("spaces")}
    knowledge_cols = {c["name"] for c in inspector.get_columns("knowledge")}
    has_auth = bind.execute(sa.text("SELECT 1 FROM information_schema.schemata WHERE schema_name = 'auth'")).scalar()
    if has_auth:
        op.create_foreign_key('fk_auth_users', 'users', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    if 'slug' in spaces_cols:
        op.create_index('idx_spaces_user_slug', 'spaces', ['user_id', 'slug'], unique=False, postgresql_where='(slug IS NOT NULL)')
    if 'is_default' in spaces_cols:
        op.create_index('idx_spaces_user_one_default', 'spaces', ['user_id'], unique=False, postgresql_where='(is_default = true)')
    if 'user_id' in knowledge_cols:
        op.create_index('idx_knowledge_user_id', 'knowledge', ['user_id'], unique=False)
    if 'space_id' in knowledge_cols:
        op.create_index('idx_knowledge_space_id', 'knowledge', ['space_id'], unique=False)
    if 'source_chunk_id' in knowledge_cols:
        op.create_index('idx_knowledge_source_chunk_id', 'knowledge', ['source_chunk_id'], unique=False)
    if 'document_id' in knowledge_cols:
        op.create_index('idx_knowledge_document_id', 'knowledge', ['document_id'], unique=False)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_runs', 'output_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('agent_runs', 'task_id')
    # ### end Alembic commands ###
